### ISSUE TITLE
Feature Request: customize terminal/software center commands

### ISSUE THREAD

**Issue by willgfx** [tofutech/tofumenu#14]
Allow customization of terminal/software center commands for those that are using alternative apps.

**Comment by tofutech** [comment]
Currently as this is made with GNOME integration in mind, it is not a planned feature. I may look into it at a later date but as of now this is not planned.

**Comment by frank-bell** [comment]
I'd also like this. I prefer to use Alacritty over the stock Gnome terminal so would be great to be able to configure the terminal used.

PS - It seems the web site link is missing from the extension ("Website" button disabled when viewing the extension in the extensions app in Gnome), so no quick and easy way to link back to this GitHub repository.

**Comment by tofutech** [comment]
As it stands it is easy enough to change the terminal command in the code but it is not a feature that is planned.
