### ISSUE TITLE
Feature: Move power options from status menu

### ISSUE THREAD

**Issue by RedBearAK** [tofutech/tofumenu#16]
I presume it was you (the author/dev) who said this on Reddit: 

>I don’t have any plans to add power options as they are in the Status Menu. 

But it would be a much better extension if you did. I would certainly appreciate it. Coming from many years of macOS, I don't like how the restart/shutdown/suspend/logout options are all lumped in with the hardware status menu options. 

What makes the Apple menu so great is that it logically groups together all the things that relate to the ENTIRE COMPUTER. In the same way, the bold "Application" menu on macOS contains options that relate to an entire application. 

What you find in the Apple menu: 
```
About This Mac
===========
System Preferences
App Store
===========
Recent Items
===========
Force Quit
===========
Sleep
Restart...
Shut Down...
===========
Lock Screen
Log Out... 
```

It doesn't really make much sense to replicate only part of this, leaving the power options stuck in the status menu with the rest of the hardware settings. 

I'd like to see something more like this (Force Quit really needs separation from other things): 

```
About My System
===========
System Settings
Software Center
Extensions
Tweaks
===========
Activities
Terminal
===========
Force Quit App
===========
Suspend
Restart...
Power Off....
===========
Lock Screen
Log Out
Switch User...
```

The three dots on certain items are important indicators that the option will bring up a secondary dialog for some kind of confirmation or interaction. This seems to be part of the Human Interface Guidelines (HIG) in both macOS and GNOME.

**Comment by tofutech** [comment]
I've thought about adding user options in the past but at the end of the day I'm trying to move away from it being a direct clone of the Apple Menu. The functionality is already in the status menu and it's something I deliberately took out of the original code so as not to duplicate functionality.
