### ISSUE TITLE
Customization of the menu

### ISSUE THREAD

**Issue by blackjackshellac** [tofutech/tofumenu#17]
It would be nice if the user could select what items to enable in the menu.

For example, I don't use gnome software so it would be nice to have a switch to turn that off.  Similarly for "Force Quit App".

It would be nice to have both Activities and Applications overview menu items

The ability to add user customizable labels and actions might also be nice, although that feature would be low on my priority list.  Perhaps the two final items could be configured as default user customizable additions, Terminal and Extensions to launch gnome-terminal and gnome-extensions-app respectively.

**Comment by tofutech** [comment]
As of now this is not something I have planned, as this was made with tight integration with GNOME in mind. The code itself is editable and easy enough to change.
