### ISSUE TITLE
Force Quit App option requires about 3-5 tries to work

### ISSUE THREAD

**Issue by JustCryen** [tofutech/tofumenu#19]
### To reproduce

**What I did**
- I clicked on the "Force Quit App" button in the menu

**What's supposed to happen**
- It should spawn `xkill`

**What happened**
- Nothing, I had to try a couple of times to get it working but it eventually spawned `xkill`

### Description

I have no idea why it doesn't work first time because in the `extension.js` it's just a simple
```
function _forceQuit() {
	Util.spawn(['xkill'])
}
```
Typing `xkill` in the terminal or `alt` + `f2` menu always works first time.

### System information
- OS: Archlinux
- gnome-shell version: 1:40.2-1
- tofumenu version: 2 (from extensions.gnome.org)

### Unrelated (sorry)

Your Discord server suddenly disappeared from my server list.
Also the link in this git page is expired, do you plan to keep it going?
Although the community was quite quiet I really enjoyed being a part of your little place.

Sorry for including this in the issue but I couldn't pm you about it (server is gone and we weren't "friends")

**Comment by tofutech** [comment]
I abandoned GNOME after some Fedora issues, so this project isn't currently being maintained by me.
