### ISSUE TITLE
Deprecation of `gnome-screensaver-command`

### ISSUE THREAD

**Issue by theEndurance-del** [tofutech/tofumenu#24]
From what I know of, the `gnome-screensaver-command` (used to lock the screen) has been deprecated in GNOME 40.
Can it be update to use `dbus` to lock the screen like so:
``` bash
dbus-send --session --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
```

**Comment by tofutech** [comment]
This project is no longer maintained.
